// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkczrRhVIjWAUHde_yBet-2SnDBvQ9cBY',
    appId: '1:408651639051:web:34523fb6cc510feb54da0e',
    messagingSenderId: '408651639051',
    projectId: 'plantsnap-e9a7f',
    authDomain: 'plantsnap-e9a7f.firebaseapp.com',
    storageBucket: 'plantsnap-e9a7f.appspot.com',
    measurementId: 'G-9Q6H5M6J92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkUr1R6rHRHQ8EVbCVr9M-l09lL2LWunQ',
    appId: '1:408651639051:android:468a2df506bcad8154da0e',
    messagingSenderId: '408651639051',
    projectId: 'plantsnap-e9a7f',
    storageBucket: 'plantsnap-e9a7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDHw-MSO0bvLP-mA-FFcfNpz1gbaKMgCs',
    appId: '1:408651639051:ios:e6ef28eae9d8f57a54da0e',
    messagingSenderId: '408651639051',
    projectId: 'plantsnap-e9a7f',
    storageBucket: 'plantsnap-e9a7f.appspot.com',
    iosBundleId: 'com.example.plantsnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDHw-MSO0bvLP-mA-FFcfNpz1gbaKMgCs',
    appId: '1:408651639051:ios:e6ef28eae9d8f57a54da0e',
    messagingSenderId: '408651639051',
    projectId: 'plantsnap-e9a7f',
    storageBucket: 'plantsnap-e9a7f.appspot.com',
    iosBundleId: 'com.example.plantsnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkczrRhVIjWAUHde_yBet-2SnDBvQ9cBY',
    appId: '1:408651639051:web:98ca8e3cf05544fa54da0e',
    messagingSenderId: '408651639051',
    projectId: 'plantsnap-e9a7f',
    authDomain: 'plantsnap-e9a7f.firebaseapp.com',
    storageBucket: 'plantsnap-e9a7f.appspot.com',
    measurementId: 'G-VBPRGK465P',
  );
}
